-- Drop view that depends on role column
DROP VIEW IF EXISTS user_activity;

-- Create permissions table
CREATE TABLE permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    module VARCHAR(50) NOT NULL
);

-- Create roles table
CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- Create role_permissions join table
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(permission_id) ON DELETE CASCADE
);

-- Insert default Permissions
-- Inventory Module
INSERT INTO permissions (name, description, module) VALUES 
('ITEM_READ', 'View items and details', 'INVENTORY'),
('ITEM_CREATE', 'Create new items', 'INVENTORY'),
('ITEM_UPDATE', 'Update existing items', 'INVENTORY'),
('ITEM_DELETE', 'Delete items', 'INVENTORY'),
('CATEGORY_MANAGE', 'Manage categories', 'INVENTORY');

-- Stock Module
INSERT INTO permissions (name, description, module) VALUES 
('STOCK_IN', 'Process stock in', 'STOCK'),
('STOCK_OUT', 'Process stock out', 'STOCK'),
('STOCK_ADJUST', 'Adjust stock levels', 'STOCK'),
('STOCK_READ', 'View stock levels', 'STOCK');

-- Orders Module
INSERT INTO permissions (name, description, module) VALUES 
('ORDER_READ', 'View orders', 'ORDERS'),
('ORDER_CREATE', 'Create orders', 'ORDERS'),
('ORDER_APPROVE', 'Approve orders', 'ORDERS');

-- System Module
INSERT INTO permissions (name, description, module) VALUES 
('USER_READ', 'View users', 'SYSTEM'),
('USER_MANAGE', 'Create, update, delete users', 'SYSTEM'),
('ROLE_MANAGE', 'Manage roles and permissions', 'SYSTEM'),
('GRADE_MANAGE', 'Manage grades', 'SYSTEM'),
('SETTINGS_MANAGE', 'Manage system settings', 'SYSTEM');

-- Insert default Roles
INSERT INTO roles (name, description) VALUES 
('Administrator', 'Full system access'),
('Standard User', 'Basic access to inventory and stock operations');

-- Assign Permissions to Administrator (All Permissions)
INSERT INTO role_permissions (role_id, permission_id)
SELECT (SELECT role_id FROM roles WHERE name = 'Administrator'), permission_id
FROM permissions;

-- Assign Permissions to Standard User
INSERT INTO role_permissions (role_id, permission_id)
SELECT (SELECT role_id FROM roles WHERE name = 'Standard User'), permission_id
FROM permissions
WHERE name IN ('ITEM_READ', 'STOCK_READ', 'ORDER_READ', 'USER_READ', 'ITEM_CREATE', 'STOCK_IN', 'STOCK_OUT');

-- Alter Users table to reference Roles
ALTER TABLE users ADD COLUMN role_id_new BIGINT;

-- Migrate existing users to new roles based on old enum
-- Map 'ROLE_ADMIN' to 'Administrator'
UPDATE users 
SET role_id_new = (SELECT role_id FROM roles WHERE name = 'Administrator')
WHERE role = 'ADMIN';

-- Map 'ROLE_USER' to 'Standard User'
UPDATE users 
SET role_id_new = (SELECT role_id FROM roles WHERE name = 'Standard User')
WHERE role = 'USER';

-- Handle any users that might not match (fallback to Standard User)
UPDATE users 
SET role_id_new = (SELECT role_id FROM roles WHERE name = 'Standard User')
WHERE role_id_new IS NULL;

-- Add Foreign Key constraint
ALTER TABLE users 
ADD CONSTRAINT fk_users_role 
FOREIGN KEY (role_id_new) REFERENCES roles(role_id);

-- Drop old role column and rename new one
ALTER TABLE users DROP COLUMN role;
ALTER TABLE users RENAME COLUMN role_id_new TO role_id;

-- Recreate user_activity view
CREATE VIEW user_activity AS
SELECT 
  u.user_id,
  u.username,
  u.email,
  r.name as role,
  COUNT(DISTINCT al.audit_log_id) as total_actions,
  MAX(al.created_at) as last_action_date
FROM users u
LEFT JOIN roles r ON u.role_id = r.role_id
LEFT JOIN audit_logs al ON u.user_id = al.user_id
GROUP BY u.user_id, u.username, u.email, r.name;
